### ISSUE TITLE
Need Swift version

### ISSUE THREAD

**Issue by lijing89** [hui-z/flutter_install_plugin#27]
`install_plugin` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod

**Comment by lijing89** [comment]
- `install_plugin` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:578:in `validate_targets'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:158:in `install!'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/lib/cocoapods/command/install.rb:51:in `run'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
    /Users/lijing/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install

**Comment by lijing89** [comment]
原因是OC项目没有桥接swift,参考:http://www.freesion.com/article/3401520/#_200
