### ISSUE TITLE
 MissingPluginException(No implementation found for method installApk on channel install_plugin)

### ISSUE THREAD

**Issue by stefanJi** [hui-z/flutter_install_plugin#3]
Platform: Android
 OS: 8.1.0

MissingPluginException(No implementation found for method installApk on channel install_plugin)

Log as follow:

```
E/flutter (17248): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (17248): MissingPluginException(No implementation found for method installApk on channel install_plugin)
E/flutter (17248): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter (17248): <asynchronous suspension>
E/flutter (17248): #1      InstallPlugin.installApk (package:install_plugin/install_plugin.dart:19:27)
```

**Comment by akindone** [comment]
Thanks for reporting. Can you check some question as list here https://github.com/flutter/flutter/issues/10912#issuecomment-310499594

**Comment by stefanJi** [comment]
I had fix  by follow that comment.
