### ISSUE TITLE
Error: Reply already submitted when install 2 apps at the same time

### ISSUE THREAD

**Issue by nvtphong200401** [hui-z/flutter_install_plugin#68]
When I install 2 other apps at the same time, it crashed my app. Please fix this issue

`
E/AndroidRuntime(17875): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1024, result=-1, data=Intent { (has extras) }} to activity {vn.vietmap.store.dev/com.example.store.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(17875): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4949)
E/AndroidRuntime(17875): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4990)
E/AndroidRuntime(17875): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(17875): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17875): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17875): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2039)
E/AndroidRuntime(17875): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17875): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17875): 	at android.app.ActivityThread.main(ActivityThread.java:7626)
E/AndroidRuntime(17875): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17875): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
E/AndroidRuntime(17875): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(17875): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(17875): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime(17875): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(17875): 	at com.zaihui.installplugin.InstallPlugin.handleActivityResult(InstallPlugin.kt:168)
E/AndroidRuntime(17875): 	at com.zaihui.installplugin.InstallPlugin.onAttachedToActivity$lambda-0(InstallPlugin.kt:49)
E/AndroidRuntime(17875): 	at com.zaihui.installplugin.InstallPlugin.$r8$lambda$jKBUQ_8YVbqu9QNsb7He6VfsHNU(Unknown Source:0)
E/AndroidRuntime(17875): 	at com.zaihui.installplugin.InstallPlugin$$ExternalSyntheticLambda1.onActivityResult(Unknown Source:2)
E/AndroidRuntime(17875): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime(17875): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime(17875): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
`

**Comment by nvtphong200401** [comment]
Note that I call for the install method on background

**Comment by JacobJustDo** [comment]
I also encountered this problem. Is there any solution？Or i can only use another plugin?
